### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by stanleylew5** [acm-ucr/witl-website#13]
![image](https://github.com/acm-ucr/witl-website/assets/135681592/eb66597d-8c7d-48ee-9d50-5e1c5152a53f)

about us page

ignore the image at the bottom that overlaps

ignore the text witl in the center of the O as well

remember to use p tags, if you want to change the font size, look it up on tailwind!!

**Comment by justin-h-im** [comment]
To-Do:
Custom spacing for ABOUT US text, both in between the letters and the vertical spacing between the two words.
Work so far:
![image](https://github.com/acm-ucr/witl-website/assets/93964548/2e3bb9d5-fab4-44e0-9eca-be378e575b0b)
![image](https://github.com/acm-ucr/witl-website/assets/93964548/dd395de0-8eb7-4ba4-b645-9ab7286f027f)
![image](https://github.com/acm-ucr/witl-website/assets/93964548/dff45b2f-f6e3-4313-b8aa-52acafb59f63)
