### ISSUE TITLE
fixes for main page blurb on all screens

### ISSUE THREAD

**Issue by stanleylew5** [acm-ucr/witl-website#203]
![image](https://github.com/user-attachments/assets/b24e53e9-aab1-425a-81d1-74c201957d19)

make sure "stands" in this blurb is right after the "law" so you'll have to bring it up -- not on the figma 

make sure there isn't a newline created just for are

**Comment by justin-h-im** [comment]
fixed mobile: 
![Womxn In The Law (1)](https://github.com/user-attachments/assets/e5e5efe0-76d1-47ca-a985-a028b2804325)
